# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

jetbrains:
  intellij:
    plugins:
      - zielu.gittoolbox
      - izhangzhihao.rainbow.brackets
