# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - command: python3 -m http.server 3000
  - command: python3 -m http.server 4000
  - command: python3 -m http.server 5000

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 4000
    onOpen: open-browser
  - port: 5000
    onOpen: ignore
