image: gitpod/workspace-postgres
tasks:
  - name: One
    env:
      - ONE: one
        TWO: 2
        THREE: "three"
    command: echo $TEST
  - name: Two
    command: DANGEROUSLY_DISABLE_HOST_CHECK=true npm start